# Generated by Django 5.0.7 on 2024-07-13 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SubVariantID', models.BigIntegerField(unique=True)),
                ('size', models.IntegerField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'sub-variant',
                'verbose_name_plural': 'sub-variants',
                'db_table': 'products_subvariant',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('VariantID', models.BigIntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='Product.products')),
                ('subvariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_products', to='Product.subvariant')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'db_table': 'products_productvariant',
            },
        ),
    ]
