# Generated by Django 5.0.7 on 2024-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_subvariant_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvariant',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subvariant',
            name='size',
            field=models.SmallIntegerField(),
        ),
    ]
