# Generated by Django 5.0.7 on 2024-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_subvariant_color_alter_subvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='Stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
