# Generated by Django 5.0.7 on 2024-07-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_productvariant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='VariantID',
        ),
        migrations.RemoveField(
            model_name='subvariant',
            name='SubVariantID',
        ),
    ]
