# Generated by Django 5.0.7 on 2024-07-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_productvariant_subvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ProductImage',
        ),
    ]
