# Generated by Django 5.0.7 on 2024-07-16 10:35

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_products_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ProductImage',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
